# Generated by Django 6.0.6 on 2026-06-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('birt_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
